### ISSUE TITLE
Package Not Found!

### ISSUE THREAD

**Issue by Skillz4Killz** [KlasaCommunityPlugins/contact#1]
```js
Home:xxxx Skillz$ npm i @kcp/functions
npm ERR! code E404
npm ERR! 404 Not Found: @kcp/functions@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxx/.npm/_logs/2019-03-26T02_49_33_280Z-debug.log
```

**Comment by QuantumlyTangled** [comment]
And compiling now works as I added the prepare script

**Comment by Skillz4Killz** [comment]
@vladfrangu I can understand that but in the future, I would recommend not updating master/Readme because anyone finding this now will have this issue. I know this is a one time issue but it is something important to keep in mind. Master should always be kept production ready at all times. That's why branches exist hehe!

**Comment by vladfrangu** [comment]
`Master should always be kept production ready at all times` Allow me to disagree. Master is the live development branch, not a production ready to use branch. I could do a breaking change right now, and you'd have issues if you were using the master branch. 

Our plugins seem to now come with a script that runs after install if it's a git dependency. While I don't like the fact we need to provide that, here we are. 

Should we do a branch that gets built from every one of our successful pushes? I could easily implement that, and that would work too. Call the branch bleeding-edge, npm has stable builds that are 100% sure to work.

Thoughts? @KlasaCommunityPlugins/plugin-creators

**Comment by bdistin** [comment]
The used method won't work on machines that don't have typescript installed globally. The way to do what you are trying to do is to include typescript in your dependencies, and use a postInstall script to run tsc like this: <https://github.com/jj09/tsc-postinstall/blob/master/package.json>... However, this means that you have to publish full TS files to npm, and your bundle now includes typescript in your dependency tree. And if you do it halfway, your post install will still try to run on your hopefully correctly npmignored source, causing install errors.

As you can imagine, this is not ideal, which is why the whole idea isn't the best practice.

Similarly, publishing builds in anything other than releases (zipped) isn't a best practice either, as GitHub is a __source__ control software, not a package manager. gh-pages, and similar branches being the exception to that rule.

The real solution is to wait for npm to respond, and then to utilize npm tags to release beta versions if that's your prerogative. So long as 2fa isn't involved in your publish flow, you can automate publishing beta builds to npm with azure pipelines when new commits are published to master. (much like pushing to stable releases a new version of the klasa vscode extension to the microsoft marketplace).

__edit:__ Actually you would have to depend on d.js/klasa directly too to be able to compile at install time, which will break the whole plugin system klasa has... (They have to be peer only in an install situation) So this method won't even work in the way proposed here or in my first paragraph.

**Comment by Skillz4Killz** [comment]
@vladfrangu I don't mind if `Master` itself isn't production but there should be a "stable" working branch at all times that won't break with every potential push. 

Take the case right now. Every single plugin is broke until NPM fixes it. If there was a separate branch `stable`(name it whatever u want), where the stable code was we could still wait for NPM and still have a working product for users. As of right now, the plugins are unusable.

**Comment by vladfrangu** [comment]
`Every single plugin is broke until NPM fixes it.` it's not NPMs job to fix our bugs. I am waiting on NPM to give me a resolution for the `@kcp` handle, which, as they said, can take 4 weeks (to give the owner time to respond). The plugins work just fine, you just need to compile them (aka run tsc in the root dir)

`where the stable code was we could still wait for NPM and still have a working product for users` I agree and disagree for this. Generally you don't have a branch of what would literally go on NPM (so like... basically a tsc output in a branch...) as you generally do that only for GitHub pages, as Ao said.

Are all plugins unusable right now? Absolutely. I 100% agree with you there. But to implement this build-a-branch thing, I'd need to go through all 13 repositories (11? TS ones) and deploy an azure change to also build ts. I can do that, but I'd rather not for something that will be temporary.

As a workaround for now (this issue will be closed immediately after I get the npm handle, or a new one if needed), after running `npm i KlasaCommunityPlugins/<plugin>` run `cd node_modules/<plugin> && tsc && cd ../../`. This will build the module and let you use it as intended.

**Comment by vladfrangu** [comment]
@QuantumlyTangled please remove the `prepare` script from modules, per the issue mentioned by @bdistin ❤️

> Actually you would have to depend on d.js/klasa directly too to be able to compile at install time, which will break the whole plugin system klasa has... (They have to be peer only in an install situation) So this method won't even work in the way proposed here or in my first paragraph.

**Comment by vladfrangu** [comment]
This has been solved as of today! https://www.npmjs.com/org/kcp
